[package]
name = "mailparse"
version = "0.7.0"
authors = ["Kartikaya Gupta <kats@seldon.staktrace.com>"]
description = "A simple parser for MIME e-mail messages"
documentation = "https://docs.rs/mailparse/"
homepage = "https://github.com/staktrace/mailparse/blob/master/README.md"
repository = "https://github.com/staktrace/mailparse"
readme = "README.md"
keywords = ["parser", "email", "rfc822", "mime", "maildir"]
categories = ["email", "parsing"]
license = "0BSD"
exclude = ["target/doc/**", ".gitattributes"]

[badges]
travis-ci = { repository = "staktrace/mailparse", branch = "master" }
maintenance = { status = "passively-maintained" }

[dependencies]
base64 = "0.10.0"
quoted_printable = "0.4.1"
charset = "0.1.1"
